export const SOURCES = {
    MAGICEDEN: 'magiceden.io',
};

export const LABELS = {
    MAGICEDEN_BASIC: 'MAGICEDEN_BASIC',
    MAGICEDEN_SALES: 'MAGICEDEN_SALES',
    MAGICEDEN_LISTINGS: 'MAGICEDEN_LISTINGS',
};

export const LAMPORT = 1000000000;

